### ISSUE TITLE
PostgreSQL multiple database

### ISSUE THREAD

**Issue by Gavin-OP** [l-v-yonsama/db-notebook#14]
for one host, there might exist multiple database. How to connect the multiple database all at once? Thank you!!

**Comment by Gavin-OP** [comment]
or how to hide the other database in the same host? Thanks!

**Comment by l-v-yonsama** [comment]
Hi, @Gavin-OP .

For PostgreSQL, the resource tree is now displayed only for the database specified in the connection definition, similar to DBeaver .
Please try it after extension upgrading ver0.7.21.

<img width="324" alt="スクリーンショット 2024-10-30 20 25 47" src="https://github.com/user-attachments/assets/728ebd21-ebec-4cc0-a571-41749b54f41c">

**Comment by Gavin-OP** [comment]
Thanks!! If there is a option that it can be set to show all databases or just show the written one, just like DBeaver, that will be great!

**Comment by l-v-yonsama** [comment]
Hi, @Gavin-OP .

> for one host, there might exist multiple database. How to connect the multiple database all at once? Thank you!!

As a limitation of the library we are using, we cannot connect to multiple databases with a single connection definition.
Please create a connection setting for each database you wish to connect to.

> how to hide the other database in the same host?

This issue was supported in ver 0.7.21.

> If there is a option that it can be set to show all databases or just show the written one, just like DBeaver.

I do not plan to support the acquisition of resources even under the Database, which is used infrequently other than the default.

It takes extra time to retrieve resources.
Even if we retrieve the resource and put it in the candidate list for IntelliSense, it is a resource that is not the default database, so even if it appears in the candidate list, it will not be selected, so all we get is noise.

Sorry I did not meet your expectations.
