### ISSUE TITLE
Output RESULTSETS initializing false

### ISSUE THREAD

**Issue by Gavin-OP** [l-v-yonsama/db-notebook#16]
When the dataset is relatively large, when click the `Open outputs`, in the `RESULTSETS`, sometimes it will show `Initializing...false`. 

![initializing_false](https://github.com/user-attachments/assets/95515bd3-e708-42f3-8004-0f7d149b04fa)

Thanks

**Comment by l-v-yonsama** [comment]
Hi @Gavin-OP .

The process of generating large amounts of data for useless and invisible data has been improved. As a result, we've confirmed that we can display data for as many as 50,000 cases.


![50000](https://github.com/user-attachments/assets/c3157cad-f2db-4603-9563-d1c2c57227fd)


Please try it after extension upgrading ver0.7.25.

**Comment by Gavin-OP** [comment]
perfect. Thanks

**Comment by jnhyeon** [comment]
① If I add LIMIT 10 to the query I used initially, the output comes out quickly.
The data_tm column is in msec units, but it only comes out up to sec.

② If I don't use the to_timestamp() function, the output comes out well.
However, only 10 are output.. and even though it took a long time to execute, it incorrectly comes out as 0.00sec.

Thank you.

![Image](https://github.com/user-attachments/assets/da8eb5d7-9724-4f12-9e03-3f5a64bce6e2)

**Comment by l-v-yonsama** [comment]
Hi @jnhyeon .

Regarding ①.
It was the specification that only up to seconds were output, but we have added an option to display milliseconds as well from the settings screen, so please use it.

Regarding ②.
I think that 11,287,560 entries is simply too much data.

The browser uses “virtual table” technology to generate the DOM only for the portion that is visible on the screen.
Even taking this into account, isn't the OOM dying because there is too much data?

I think the limit is about 100,000 records, and if you want more than that, I hope you can use DBeaver.

<img width="630" alt="Image" src="https://github.com/user-attachments/assets/6ff8773e-6f22-4eb4-8a1a-969542f5166b" />

<img width="1406" alt="Image" src="https://github.com/user-attachments/assets/c6df403a-8664-4032-b067-31edb4226f73" />

**Comment by jnhyeon** [comment]
I will try to use it by setting the timestamp to display up to msec.

In case of a lot of data, I will use the LIMIT keyword to output it appropriately.

Thank you very much :)
